services:
  - type: web
    name: iceberg-backend
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: iceberg-backend
    region: frankfurt
    plan: free
    rootDir: iceberg-backend
    healthCheckPath: /health
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: MASTER_API_KEY
        sync: false
      - key: PORT
        value: "8000"
